version: 2.1

orbs:
  python: circleci/python@1.3.4
  sam: circleci/aws-sam-serverless@3.0.0
  
jobs:
  
  run-unit-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements/test.txt
          pkg-manager: pip
      - run:
          command: |
            python -m pytest tests/ -v

workflows:
  test-and-deploy:
    jobs:
      - run-unit-test:
          name: run-unit-test
      - sam/deploy:
          context: aws-credentials-context
          name: deploy-staging
          s3-bucket: braindump-identity
          stack-name: staging-braindump-identity
          template: ./template.yaml  

