version: 2.1

orbs:
  python: circleci/python@1.3.4
  aws-sam-serverless: circleci/aws-sam-serverless@3.0.0
  

jobs:
  
  run-unit-test:
    executor: python/default
    steps:
      - run:
          command: |
            python -m pytest tests/ -v

  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements/test.txt
          pkg-manager: pip
      - run-unit-test

workflows:
  main:
    jobs:
      - build-and-test
