version: 2.1

orbs:
  python: circleci/python@1.3.4

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependancy-file: requirements/test.txt
          pkg-manager: pip
      - run:
          command: |
            pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
