version: 2.1

orbs:
  python: circleci/python@1.3.4
  aws-sam-serverless: circleci/aws-sam-serverless@3.0.0
  

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements/test.txt
          pkg-manager: pip
      - run:
          command: |
            pytest
          name: Test

workflows:
  main:
    jobs:
      - test:
          pip-dependency-file: requirements/test.txt
          pkg-manager: pip
          test-tool: pytest
          version: '3.7'
