version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    args: '--dev'
    pkg-manager: pipenv
    test-tool: pytest
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

workflows:
  main:
    jobs:
      - build-and-test
